/**
 * Nino Chavez ⊕ studio — Tailwind CSS Preset
 * Generated by brand-forge v0.2.0
 * DO NOT EDIT — regenerate with: brand-forge export tailwind
 */

/** @type {import("tailwindcss").Config} */
export default {
  theme: {
    extend: {
      colors: {
        primary: '#f5b91a',
        secondary: '#5a9a4e',
        accent: '#d94c35',
        neutral: {
          '50': '#fafafa',
          '100': '#f5f5f5',
          '200': '#e5e5e5',
          '300': '#d4d4d4',
          '400': '#a3a3a3',
          '500': '#737373',
          '600': '#525252',
          '700': '#404040',
          '800': '#262626',
          '900': '#171717',
          '950': '#0a0a0a',
        },
        success: '#4a7c3f',
        warning: '#f97316',
        error: '#ef4444',
        info: '#3b82f6',
        surface: {
          'background': '#0a0a0a',
          'foreground': '#fafafa',
          'card': '#171717',
          'card-foreground': '#fafafa',
          'muted': '#262626',
          'muted-foreground': '#a3a3a3',
          'border': '#404040',
        },
      },
      fontFamily: {
        display: ['Bebas Neue', 'Impact', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Space Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'hero': ['6rem', { lineHeight: '0.9', fontWeight: '400' }],
        'h2': ['3.5rem', { lineHeight: '1', fontWeight: '400' }],
        'h3': ['1.5rem', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label': ['0.75rem', { lineHeight: '1.4', fontWeight: '700' }],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '6': '1.5rem',
        '8': '2rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
      },
      borderRadius: {
        none: '0',
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      maxWidth: {
        content: '80rem',
      },
    },
  },
};