/**
 * Nino Chavez ⊕ studio — Tailwind CSS Preset
 * Generated by brand-forge v0.1.0
 * DO NOT EDIT — regenerate with: brand-forge export tailwind
 */

/** @type {import("tailwindcss").Config} */
export default {
  theme: {
    extend: {
      colors: {
        primary: '#e86c5d',
        secondary: '#4a90bb',
        accent: '#d4a574',
        neutral: {
          '50': '#fafafa',
          '100': '#f5f5f5',
          '200': '#e5e5e5',
          '300': '#d1d5db',
          '400': '#a3a3a3',
          '500': '#6b7280',
          '600': '#525252',
          '700': '#374151',
          '800': '#262626',
          '900': '#111827',
          '950': '#0a0a0f',
        },
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
        surface: {
          'background': '#0f1419',
          'foreground': '#e8eaed',
          'card': '#111827',
          'card-foreground': '#e8eaed',
          'muted': '#1f2937',
          'muted-foreground': '#9ca3af',
          'border': '#374151',
        },
      },
      fontFamily: {
        display: ['Roboto Slab', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'hero': ['4rem', { lineHeight: '1.1', fontWeight: '700' }],
        'h2': ['2.25rem', { lineHeight: '1.2', fontWeight: '400' }],
        'h3': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label': ['0.75rem', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '6': '1.5rem',
        '8': '2rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
      },
      borderRadius: {
        none: '0',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      maxWidth: {
        content: '48rem',
      },
    },
  },
};